// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
//  // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIyQ9DCua5LSOcSkhO8-1NhC2GUdozqhA',
    appId: '1:953738935180:android:0d210ed11891b75b18f4a9',
    messagingSenderId: '953738935180',
    projectId: 'frutality',
    storageBucket: 'frutality.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCauTlVpJwbkpMGu-cluZuQb81jiTrJw24',
    appId: '1:953738935180:ios:03d5e59cb28534c618f4a9',
    messagingSenderId: '953738935180',
    projectId: 'frutality',
    storageBucket: 'frutality.appspot.com',
    iosClientId: '953738935180-t4h9f3mqrif2prj7p1d8o2gs6k9ve4ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.frutality',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVkAvnzdGETgiAg-7A7Q8rPeaeRCuPr_8',
    appId: '1:953738935180:web:e23b55c49bfbd76718f4a9',
    messagingSenderId: '953738935180',
    projectId: 'frutality',
    authDomain: 'frutality.firebaseapp.com',
    storageBucket: 'frutality.appspot.com',
    measurementId: 'G-8H5PZW02K1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVkAvnzdGETgiAg-7A7Q8rPeaeRCuPr_8',
    appId: '1:953738935180:web:b4133b019f8ff39618f4a9',
    messagingSenderId: '953738935180',
    projectId: 'frutality',
    authDomain: 'frutality.firebaseapp.com',
    storageBucket: 'frutality.appspot.com',
    measurementId: 'G-5Z7HCPL8WP',
  );

}